# Preface

Scientific research has become increasingly complex, requiring specialized skills, interdisciplinary work, and collaboration among large teams. Managing such projects and tracking data and metadata has become a significant challenge. The need for FAIR (findable, accessible, interoperable, and reusable) open data, materials, and metadata has similarly grown -- especially considering recent mandates for required sharing for federally funded projects. While user-friendly software tools that help researchers structure metadata exist, few researchers are aware of their necessity and usefulness---the onus is still on the project team to collect and curate this information. Studies using teams of researchers require sophisticated tracking of all project elements, and therefore, there is a need for scientific project management software that is tailored to the management of all manner of science projects. Software that promotes best practices in FAIR data and metadata would increase openness in all reporting, and tracking, and reporting standards.

Currently, the tools and websites designed for researchers are focused on *getting* researchers to share their materials, code, and data (i.e., Open Science Framework (osf.io), FigShare, Zenodo). These repositories represent a necessary resource for long-term storage of outputs, but do not help researchers organize or track information during the life of a study. Project management software, like Asana, Monday, or ClickUp, are designed from a business perspective that is not tailored to scientific research. While the features that scientific research requires may be found in some individual project management software, no current solution provides all the essential features, such as the ability to assign tasks at different scales (e.g., teams, individuals), integrated metadata, fully transparent access to all information in the project manager, and long-term storage that complies with international data privacy regulations. Project management software is designed to *get things done* rather than *document* the way a project was completed, so attempts to use existing software for this often involve 'hacking' it to extract necessary records.

This project aims to develop a science focused project management tool, called STAPLE, that not only helps with the unique challenges of project management of research but includes open and transparent documentation of data and metadata, as well as proposing minimum metadata standards. STAPLE will have the ability to add project components based on research type, assign timelines, assign tasks to users/groups, link to long-term storage of research outputs, and interface with relevant application interfaces to track authorship credit. STAPLE will also include default metadata standards for documentation of common research outputs, be open-source, and allow for community input. The project aims to have a global impact by promoting the transformation to open science and including researchers and their works that may be commonly ignored, regardless of technical capabilities, so that it is open to everyone. By creating software that allows a point and click interface with error feedback and automated validation, we will promote inclusivity within the scientific community by enabling everyone to participate in transparency and openness.
