# Introduction

```{r echo = F}
library(glossary) 
glossary_persistent(path = "glossary/glossary-persistant.yml")
glossary_popup("hover")
```

The STAPLE mission: *Project Management* software that allows you to *document* your research project to improve *transparency*.

As researchers, we must balance attention to the big picture: the overarching goals, timelines, theories, and hypotheses of a project, with the smaller goals and tasks required to realize those ambitions. While most researchers receive training in designing studies, collecting and analyzing data, and publishing findings, formal instruction in project management is rare. Instead, these skills are often acquired informally, modeled within the research lab environment and shaped by a supervisor’s style. Each project also introduces unique needs and circumstances, and even the addition of a single collaborator can generate new layers of coordination and complexity.

Evidence indicates that the number of co-authors and collaborators on research projects has increased steadily over time [@wuchty2007]. Advances in digital communication and collaboration tools such as Zoom, GitHub, and Google Workspace, combined with the globalization of research, have enabled teams to work together across great distances and disciplinary boundaries [@cummings2005; @cummings2007]. Large-scale collaborations are increasingly encouraged, not only to tackle ambitious scientific questions, but also to enhance the diversity of participants, researchers, and cultures represented in data [@moshontz2018; @swartz2019; @adan2023]. The inclusion of multiple collaborators, each embedded in different lab cultures, institutions, geopolitical contexts, and languages, increases the complexity of managing research projects.

*So why do we need software*?

General project management platforms, such as Asana, Monday, ClickUp, and Trello, are widely used in business settings, but they were designed around business-oriented workflows and templates. Research projects, however, present unique challenges that do not map neatly onto these models. Scientific projects often require coordination of specialized tasks such as research design, ethical approval, data collection across multiple sites, `r glossary("metadata")` documentation, open data sharing, and publication requirements [@borghi2021; @fecher2014].

Large-scale collaborations have experimented with adapting existing structures, sometimes treating multi-team projects like classrooms or leveraging educational technologies, but these solutions are partial fits at best. What researchers need is a system that recognizes the scientific lifecycle: from ideas and preregistration, to data collection, to analysis, dissemination, and long-term archiving. STAPLE is designed for scientists, by scientists. It was built with input not only from researchers but also from key stakeholders in the broader research ecosystem, including funders, librarians, and journals, ensuring that the software supports transparency, reproducibility, and effective project management across diverse scientific contexts.

*So what's the deal with documentation*?

In tandem with the encouragement for interdisciplinary, diverse teams, researchers have begun to focus on the improvement of science through transparency and sharing. The `r glossary("Transparency and Openness")` guidelines establish ideals for projects to be reproducible, open, and transparency through data sharing, code/analysis sharing, materials sharing, pre-registration, and replication [@grant]. Journals require different levels of sharing for publication, which has pushed researchers to begin to implement these practices. However, the simple sharing of data, code, and materials does not make them `r glossary("FAIR")`: Findable, Accessible, Interoperable, and Reusable [@wilkinson2016]. Simple sharing of data does not necessarily allow someone to find that data in relation to the research project, or allow a researcher to know what `V1` means in the data, or even reuse part of the data.

Creating adequate documentation for the reuse of any output from a project can be difficult. There are often no clear standards, the work can be time consuming, and is often left to the end of a project when important details may have been forgotten. STAPLE is designed to encourage you to document information along the way and to provide guidance with what you should include with each document. As you complete specific task, such as create your materials for a study, you will be able to link your project to those materials and include information to interpret and understand those documents. We provide a set of minimum documentation standards for multiple types of documents - and the ability for you to include extra information if your field has set standards.

*Ok, so that's transparent*?

STAPLE allows you to track and run your project - and then include research outputs from that project. Each step of the way, STAPLE collects data about who did what and when. If you are the only person working on a project, it's simple: you will export a final project timeline that includes information about each step of the project, each output, and the documentation needed to make those outputs useful. If you work with other people, STAPLE will allow you to assign tasks to those individuals (or teams of individuals) to complete as part of the project management functionality. At the same time, STAPLE tracks their work and creates a project timeline that shows that they completed a task for the project.

This component of the software was designed to align with `r glossary("contributorship")` models of research - instead of "authorship", each person receives credit for the components they contributed to the project [@allen2014; @allen2019]. Each field has different standards for authorship, and many individual's work may not be acknowledged due to those cultures. Using STAPLE, their work would be credited, even if they did not earn final "`r glossary("authorship")`" on a publication. This output is also useful for defining contributions into systems such as `r glossary("CRediT")` - where each person's role is binned into categories. By linking each role to specific tasks, we can transparently show what each role means to a specific project.